### ISSUE TITLE
how to setup backend for ichat ,can you please describe that

### ISSUE THREAD

**Issue by Arunsubramani1607** [wissemgrari/iChat#2]

**Comment by wissemgrari** [comment]
Sorry for the confusion this project still in development cycle and I didn't write the **README** file yet, but if you want to setup the backend navigate to the **api** directory, there replace **.env.example** to **.env** and fill the the attributes with your own value, the same goes for **docker-compose.example.yml** rename it to **docker-compose.yml** and run it with docker-compose if you which to use docker.
